backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "hotels"
    label: "Hotels"
    folder: "src/pages/hotels"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: hotel-page}
      - {label: Title, name: title, widget: text}
      - {label: Image, name: image, widget: image}
      - {label: Brand, name: brand, widget: image}
      - {label: Description, name: description, widget: text}
      - {label: Destination picture, name: destination_img, widget: image}
      - {label: Destination name, name: destination_name, widget: text}
      - {label: Destination description, name: destination_description, widget: text}
      - {label: Instagram posts, name: instagram_posts, widget: list, field: {label: Instagram Images, name: instagram_images, widget: object, fields: [{label: Image, name: image, widget: Image}, {label: Link, name: link, widget: string}]}}
      - {label: Optional Content, name: content, widget: markdown, required: false}
  - name: "rooms"
    label: "Rooms"
    folder: "src/pages/rooms"
    create: true 
    fields: 
      - {label: Template Key, name: templateKey, widget: hidden, default: room-page}
      - {label: Hotel, name: hotel, widget: select, options: [beke, wayak, casaMaya] }
      - {label: Title, name: title, widget: string}
      - {label: Main Image, name: image, widget: image}
      - {label: Description, name: description, widget: object, fields: [
          {label: First Image, name: first_image, widget: image},
          {label: Tagline, name: tagline, widget: text},
          {label: Description, name: description, widget: text},
          {label: second Image, name: second_image, widget: image, required: false},
          {label: Second tagline, name: second_tagline, widget: text, required: false},
          {label: Second Description, name: second_description, widget: text, required: false}
        ]}
      - {label: Amenities, name: amenities, widget: markdown}
      - {label: Footer Image, name: footer_image, widget: image}


  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {
              label: Header,
              name: header,
              widget: object,
              fields: [
                {label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Image alt, name: img_alt, widget: string}, {label: Icon, name: icon, widget: image, required: false}, {label: Icon alt, name: icon_alt, widget: string, required: false}, {label: Caption, name: caption, widget: text, required: false}]},
                {label: Introduction, name: introduction, widget: object, fields: [{label: image, name: image, widget: image}, {label: Icon, name: icon, widget: image, required: false}, {label: Introduction caption, name: introCaption, widget: text, required: false}]}
              ] 
            }
          - {label: Title, name: title, widget: string}
          - {label: Newsletter, name: newsletter, widget: object, fields: [{label: Sentence, name: sentence, widget: string}, {label: Newsletter image, name: image, widget: image}]}
      - file: "src/pages/products/index.md"
        label: "Hotels Page"
        name: "hotels"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
          